apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - api-deployment.yaml
  - api-hpa.yaml
  - processor-deployment.yaml

commonLabels:
  app.kubernetes.io/name: retail-media-platform
  app.kubernetes.io/part-of: retail-media
